from enum import Enum

class DamageType(Enum):
    DAMAGE_NORMAL = "DAMAGE_NORMAL"
    DAMAGE_AIR = "DAMAGE_AIR"
    DAMAGE_SEA = "DAMAGE_SEA"
    DAMAGE_BUILDING = "DAMAGE_BUILDING"
    DAMAGE_HARD = "DAMAGE_HARD"
    DAMAGE_SUBMARINE = "DAMAGE_SUBMARINE"
    DAMAGE_BLAST = "DAMAGE_BLAST"
    DAMAGE_POPULATION = "DAMAGE_POPULATION"
    DAMAGE_HELICOPTER = "DAMAGE_HELICOPTER"
    DAMAGE_SIEGE = "DAMAGE_SIEGE"
    DAMAGE_CONTAMINATION = "DAMAGE_CONTAMINATION"
    DAMAGE_SOFT_NBC = "DAMAGE_SOFT_NBC"
    DAMAGE_HARD_NBC = "DAMAGE_HARD_NBC"
    DAMAGE_MISSILE = "DAMAGE_MISSILE"