"""
Constants for the Replay Debug CLI Tool.
"""

# Column widths for table formatting
COLUMN_WIDTH_INDEX = 5
COLUMN_WIDTH_PATCH = 25
COLUMN_WIDTH_PATCH_FULL = 30
COLUMN_WIDTH_DIRECTION = 8
COLUMN_WIDTH_TYPE = 8
COLUMN_WIDTH_PATH_COMPACT = 35
COLUMN_WIDTH_PATH_FULL = 60
COLUMN_WIDTH_VALUE_COMPACT = 15
COLUMN_WIDTH_TIMESTAMP = 20
COLUMN_WIDTH_OPS = 8
COLUMN_WIDTH_STATE = 35
COLUMN_WIDTH_COUNT = 10

# Default values
DEFAULT_LIMIT = 50
DEFAULT_DIRECTION = 'both'

# Shell prompt
SHELL_PROMPT = "replay-debug> "

# Separator widths
SEPARATOR_WIDTH_COMPACT = 100
SEPARATOR_WIDTH_FULL = 150
SEPARATOR_WIDTH_OVERVIEW = 90
