name: tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]


      - name: get test data
        run: |
          wget -O full_test_data_1_v206.json https://raw.githubusercontent.com/zDox/ConflictData/refs/heads/main/FullTestData/full_test_data_1_v206.json


      - name: Run tests with unittest
        env:
          TEST_ACCOUNT_USERNAME: ${{ secrets.TEST_ACCOUNT_USERNAME }}
          TEST_ACCOUNT_PASSWORD: ${{ secrets.TEST_ACCOUNT_PASSWORD }}
          TEST_ACCOUNT_EMAIL: ${{ secrets.TEST_ACCOUNT_EMAIL }}
          TEST_PROXY_URL: ${{secrets.TEST_PROXY_URL}}
        run: |
          python tests/run_tests.py
          
